name: 'Trello Manage'
description: 'Creates lists of issues in Trello'
inputs:
  repo-name:
    description: 'Repository name'
    required: true
  trello-username:
    description: 'Username of Trello Account'
    required: true
runs:
  using: 'node12'
  main: 'index.js'